import * as classnames from 'classnames';
import * as React from 'react';
import { getDataProps } from '../../../../utils/data-props';
import './styles.sass';

export enum Token {
  ColorBackground = 1,
  ColorBackgroundAlt,
  ColorBackgroundAlt2,
  ColorBackgroundLive,
  ColorBackgroundPrime,
  ColorBackgroundButton,
  ColorBackgroundButtonHover,
  ColorBackgroundButtonFocus,
  ColorBackgroundButtonActive,
  ColorBackgroundButtonDisabled,
  ColorBackgroundButtonPurchase,
  ColorBackgroundButtonHollow,
  ColorBackgroundButtonHollowHover,
  ColorBackgroundButtonHollowFocus,
  ColorBackgroundButtonHollowActive,
  ColorBackgroundButtonStatus,
  ColorBackgroundButtonStatusHover,
  ColorBackgroundButtonStatusFocus,
  ColorBackgroundButtonStatusActive,
  ColorBackgroundButtonSuccess,
  ColorBackgroundButtonSuccessHover,
  ColorBackgroundButtonSuccessFocus,
  ColorBackgroundButtonSuccessActive,
  ColorBackgroundButtonAlert,
  ColorBackgroundButtonAlertHover,
  ColorBackgroundButtonAlertFocus,
  ColorBackgroundButtonAlertActive,
  ColorBackgroundInteractable,
  ColorBackgroundInteractableHover,
  ColorBackgroundInteractableActive,
  ColorBackgroundInteractableSelected,
  ColorBackgroundInput,
  ColorBackgroundInputChecked,
  ColorBackgroundToggle,
  ColorBackgroundToggleHandle,
  ColorBackgroundToggleHover,
  ColorBackgroundToggleFocus,
  ColorBackgroundToggleChecked,
  ColorBackgroundBalloonHotspot,
  ColorBackgroundBalloonHotspotHover,
  ColorBackgroundBalloonLinkHover,
  ColorBackgroundBalloonLinkSelected,
  ColorBackgroundBalloonTooltip,
  ColorBackgroundBalloonPurple,
  ColorBackgroundBalloonAlert,
  ColorBackgroundOverlay,
  ColorBackgroundProgress,
  ColorBackgroundProgressStatus,
  ColorBackgroundProgressStatusError,
  ColorBackgroundProgressStatusCaution,
  ColorBackgroundProgressCountdown,
  ColorBackgroundProgressCountdownStatus,
  ColorBackgroundPill,
  ColorBackgroundModalOverlay,
  ColorBackgroundModal,
  ColorBackgroundSocialColumn,
  ColorBackgroundTopNav,
  ColorText,
  ColorTextAlt,
  ColorTextAlt2,
  ColorTextLink,
  ColorTextLinkHover,
  ColorTextLinkActive,
  ColorTextLinkVisited,
  ColorTextLive,
  ColorTextPrime,
  ColorTextTab,
  ColorTextTabActive,
  ColorTextButton,
  ColorTextButtonHover,
  ColorTextButtonFocus,
  ColorTextButtonActive,
  ColorTextButtonDisabled,
  ColorTextButtonSecondary,
  ColorTextButtonSecondaryHover,
  ColorTextButtonSecondaryFocus,
  ColorTextButtonSecondaryActive,
  ColorTextButtonHollow,
  ColorTextButtonHollowHover,
  ColorTextButtonHollowFocus,
  ColorTextButtonHollowActive,
  ColorTextButtonStatus,
  ColorTextButtonStatusHover,
  ColorTextButtonStatusFocus,
  ColorTextButtonStatusActive,
  ColorTextButtonSuccess,
  ColorTextButtonSuccessHover,
  ColorTextButtonSuccessFocus,
  ColorTextButtonSuccessActive,
  ColorTextButtonAlert,
  ColorTextButtonAlertHover,
  ColorTextButtonAlertFocus,
  ColorTextButtonAlertActive,
  ColorTextInteractable,
  ColorTextInteractableHover,
  ColorTextInteractableFocus,
  ColorTextInteractableActive,
  ColorTextInput,
  ColorTextInputPlaceholder,
  ColorTextInputCheckedIcon,
  ColorTextLabel,
  ColorTextLabelOptional,
  ColorTextHint,
  ColorTextToggleCheckedIcon,
  ColorTextError,
  ColorTextBalloonTitle,
  ColorTextBalloonLink,
  ColorTextBalloonLinkHover,
  ColorTextBalloonLinkDisabled,
  ColorTextBalloonLinkAlert,
  ColorTextBalloonTooltip,
  ColorTextBalloonPurple,
  ColorTextBalloonAlert,
  ColorTextOverlay,
  ColorTextOverlayAlt,
  ColorTextPill,
  ColorBorder,
  ColorBorderTab,
  ColorBorderTabHover,
  ColorBorderTabFocus,
  ColorBorderTabActive,
  ColorBorderButton,
  ColorBorderButtonHover,
  ColorBorderButtonFocus,
  ColorBorderButtonActive,
  ColorBorderButtonDisabled,
  ColorBorderButtonHollow,
  ColorBorderButtonHollowHover,
  ColorBorderButtonHollowFocus,
  ColorBorderButtonHollowActive,
  ColorBorderButtonStatus,
  ColorBorderButtonStatusHover,
  ColorBorderButtonStatusFocus,
  ColorBorderButtonStatusActive,
  ColorBorderButtonSuccess,
  ColorBorderButtonSuccessHover,
  ColorBorderButtonSuccessFocus,
  ColorBorderButtonSuccessActive,
  ColorBorderButtonAlert,
  ColorBorderButtonAlertHover,
  ColorBorderButtonAlertFocus,
  ColorBorderButtonAlertActive,
  ColorBorderInput,
  ColorBorderInputFocus,
  ColorBorderInputChecked,
  ColorBorderInputError,
  ColorBorderToggle,
  ColorBorderToggleHover,
  ColorBorderToggleFocus,
  ColorFill,
  ColorFillCurrent,
  ColorFillAlt,
  ColorFillAlt2,
  ColorFillBrand,
  ColorFillLive,
  ColorFillWarn,
  ColorFillAlert,
  ColorFillSuccess,
  ColorFillPrime,
  ColorSocialTwitter,
  ColorSocialFacebook,
  ColorSocialReddit,
  ColorSocialSnapchat,
  ColorSocialInstagram,
  ColorSocialYoutube,
  ColorSocialPaypal,
  ColorSocialVk,
  ShadowButtonFocus,
  ShadowButtonActive,
  ShadowButtonDisabled,
  ShadowInput,
  ShadowInputFocus,
  ShadowTabFocus,
  ShadowBalloon,
  BorderWidth,
  BorderRadius,
}

const TOKEN_CLASSES = {
  [Token.ColorBackground]: 'token__swatch--color-background',
  [Token.ColorBackgroundAlt]: 'token__swatch--color-background-alt',
  [Token.ColorBackgroundAlt2]: 'token__swatch--color-background-alt-2',
  [Token.ColorBackgroundLive]: 'token__swatch--color-background-live',
  [Token.ColorBackgroundPrime]: 'token__swatch--color-background-prime',
  [Token.ColorBackgroundButton]: 'token__swatch--color-background-button',
  [Token.ColorBackgroundButtonHover]: 'token__swatch--color-background-button-hover',
  [Token.ColorBackgroundButtonFocus]: 'token__swatch--color-background-button-focus',
  [Token.ColorBackgroundButtonActive]: 'token__swatch--color-background-button-active',
  [Token.ColorBackgroundButtonDisabled]: 'token__swatch--color-background-button-disabled',
  [Token.ColorBackgroundButtonPurchase]: 'token__swatch--color-background-button',
  [Token.ColorBackgroundButtonHollow]: 'token__swatch--color-background-button-hollow',
  [Token.ColorBackgroundButtonHollowHover]: 'token__swatch--color-background-button-hollow-hover',
  [Token.ColorBackgroundButtonHollowFocus]: 'token__swatch--color-background-button-hollow-focus',
  [Token.ColorBackgroundButtonHollowActive]: 'token__swatch--color-background-button-hollow-active',
  [Token.ColorBackgroundButtonStatus]: 'token__swatch--color-background-button-status',
  [Token.ColorBackgroundButtonStatusHover]: 'token__swatch--color-background-button-status-hover',
  [Token.ColorBackgroundButtonStatusFocus]: 'token__swatch--color-background-button-status-focus',
  [Token.ColorBackgroundButtonStatusActive]: 'token__swatch--color-background-button-status-active',
  [Token.ColorBackgroundButtonSuccess]: 'token__swatch--color-background-button-success',
  [Token.ColorBackgroundButtonSuccessHover]: 'token__swatch--color-background-button-success-hover',
  [Token.ColorBackgroundButtonSuccessFocus]: 'token__swatch--color-background-button-success-focus',
  [Token.ColorBackgroundButtonSuccessActive]: 'token__swatch--color-background-button-success-active',
  [Token.ColorBackgroundButtonAlert]: 'token__swatch--color-background-button-alert',
  [Token.ColorBackgroundButtonAlertHover]: 'token__swatch--color-background-button-alert-hover',
  [Token.ColorBackgroundButtonAlertFocus]: 'token__swatch--color-background-button-alert-focus',
  [Token.ColorBackgroundButtonAlertActive]: 'token__swatch--color-background-button-alert-active',
  [Token.ColorBackgroundInteractable]: 'token__swatch--color-background-interactable',
  [Token.ColorBackgroundInteractableHover]: 'token__swatch--color-background-interactable-hover',
  [Token.ColorBackgroundInteractableActive]: 'token__swatch--color-background-interactable-active',
  [Token.ColorBackgroundInteractableSelected]: 'token__swatch--color-background-interactable-selected',
  [Token.ColorBackgroundInput]: 'token__swatch--color-background-input',
  [Token.ColorBackgroundInputChecked]: 'token__swatch--color-background-input-checked',
  [Token.ColorBackgroundToggle]: 'token__swatch--color-background-toggle',
  [Token.ColorBackgroundToggleHandle]: 'token__swatch--color-background-toggle-handle',
  [Token.ColorBackgroundToggleHover]: 'token__swatch--color-background-toggle-hover',
  [Token.ColorBackgroundToggleFocus]: 'token__swatch--color-background-toggle-focus',
  [Token.ColorBackgroundToggleChecked]: 'token__swatch--color-background-toggle-checked',
  [Token.ColorBackgroundBalloonHotspot]: 'token__swatch--color-background-balloon-hotspot',
  [Token.ColorBackgroundBalloonHotspotHover]: 'token__swatch--color-background-balloon-hotspot-hover',
  [Token.ColorBackgroundBalloonLinkHover]: 'token__swatch--color-background-balloon-link-hover',
  [Token.ColorBackgroundBalloonLinkSelected]: 'token__swatch--color-background-balloon-link-selected',
  [Token.ColorBackgroundBalloonTooltip]: 'token__swatch--color-background-balloon-tooltip',
  [Token.ColorBackgroundBalloonPurple]: 'token__swatch--color-background-balloon-purple',
  [Token.ColorBackgroundBalloonAlert]: 'token__swatch--color-background-balloon-alert',
  [Token.ColorBackgroundOverlay]: 'token__swatch--color-background-overlay',
  [Token.ColorBackgroundProgress]: 'token__swatch--color-background-progress',
  [Token.ColorBackgroundProgressStatus]: 'token__swatch--color-background-progress-status',
  [Token.ColorBackgroundProgressStatusError]: 'token__swatch--color-background-progress-status-error',
  [Token.ColorBackgroundProgressStatusCaution]: 'token__swatch--color-background-progress-status-caution',
  [Token.ColorBackgroundProgressCountdown]: 'token__swatch--color-background-progress-countdown',
  [Token.ColorBackgroundProgressCountdownStatus]: 'token__swatch--color-background-progress-countdown-status',
  [Token.ColorBackgroundPill]: 'token__swatch--color-background-pill',
  [Token.ColorBackgroundModalOverlay]: 'token__swatch--color-background-modal-overlay',
  [Token.ColorBackgroundModal]: 'token__swatch--color-background-modal',
  [Token.ColorBackgroundSocialColumn]: 'token__swatch--color-background-social-column',
  [Token.ColorBackgroundTopNav]: 'token__swatch--color-background-top-nav',
  [Token.ColorText]: 'token__swatch--color-text',
  [Token.ColorTextAlt]: 'token__swatch--color-text-alt',
  [Token.ColorTextAlt2]: 'token__swatch--color-text-alt-2',
  [Token.ColorTextLink]: 'token__swatch--color-text-link',
  [Token.ColorTextLinkHover]: 'token__swatch--color-text-link-hover',
  [Token.ColorTextLinkActive]: 'token__swatch--color-text-link-active',
  [Token.ColorTextLinkVisited]: 'token__swatch--color-text-link-visited',
  [Token.ColorTextLive]: 'token__swatch--color-text-live',
  [Token.ColorTextPrime]: 'token__swatch--color-text-prime',
  [Token.ColorTextTab]: 'token__swatch--color-text-tab',
  [Token.ColorTextTabActive]: 'token__swatch--color-text-tab-active',
  [Token.ColorTextButton]: 'token__swatch--color-text-button',
  [Token.ColorTextButtonHover]: 'token__swatch--color-text-button-hover',
  [Token.ColorTextButtonFocus]: 'token__swatch--color-text-button-focus',
  [Token.ColorTextButtonActive]: 'token__swatch--color-text-button-active',
  [Token.ColorTextButtonDisabled]: 'token__swatch--color-text-button-disabled',
  [Token.ColorTextButtonSecondary]: 'token__swatch--color-text-button-secondary',
  [Token.ColorTextButtonSecondaryHover]: 'token__swatch--color-text-button-secondary-hover',
  [Token.ColorTextButtonSecondaryFocus]: 'token__swatch--color-text-button-secondary-focus',
  [Token.ColorTextButtonSecondaryActive]: 'token__swatch--color-text-button-secondary-active',
  [Token.ColorTextButtonHollow]: 'token__swatch--color-text-button-hollow',
  [Token.ColorTextButtonHollowHover]: 'token__swatch--color-text-button-hollow-hover',
  [Token.ColorTextButtonHollowFocus]: 'token__swatch--color-text-button-hollow-focus',
  [Token.ColorTextButtonHollowActive]: 'token__swatch--color-text-button-hollow-active',
  [Token.ColorTextButtonStatus]: 'token__swatch--color-text-button-status',
  [Token.ColorTextButtonStatusHover]: 'token__swatch--color-text-button-status-hover',
  [Token.ColorTextButtonStatusFocus]: 'token__swatch--color-text-button-status-focus',
  [Token.ColorTextButtonStatusActive]: 'token__swatch--color-text-button-status-active',
  [Token.ColorTextButtonSuccess]: 'token__swatch--color-text-button-success',
  [Token.ColorTextButtonSuccessHover]: 'token__swatch--color-text-button-success-hover',
  [Token.ColorTextButtonSuccessFocus]: 'token__swatch--color-text-button-success-focus',
  [Token.ColorTextButtonSuccessActive]: 'token__swatch--color-text-button-success-active',
  [Token.ColorTextButtonAlert]: 'token__swatch--color-text-button-alert',
  [Token.ColorTextButtonAlertHover]: 'token__swatch--color-text-button-alert-hover',
  [Token.ColorTextButtonAlertFocus]: 'token__swatch--color-text-button-alert-focus',
  [Token.ColorTextButtonAlertActive]: 'token__swatch--color-text-button-alert-active',
  [Token.ColorTextInteractable]: 'token__swatch--color-text-interactable',
  [Token.ColorTextInteractableHover]: 'token__swatch--color-text-interactable-hover',
  [Token.ColorTextInteractableFocus]: 'token__swatch--color-text-interactable-focus',
  [Token.ColorTextInteractableActive]: 'token__swatch--color-text-interactable-active',
  [Token.ColorTextInput]: 'token__swatch--color-text-input',
  [Token.ColorTextInputPlaceholder]: 'token__swatch--color-text-input-placeholder',
  [Token.ColorTextInputCheckedIcon]: 'token__swatch--color-text-input-checked-icon',
  [Token.ColorTextLabel]: 'token__swatch--color-text-label',
  [Token.ColorTextLabelOptional]: 'token__swatch--color-text-label',
  [Token.ColorTextHint]: 'token__swatch--color-text-hint',
  [Token.ColorTextToggleCheckedIcon]: 'token__swatch--color-text-toggle-checked-icon',
  [Token.ColorTextError]: 'token__swatch--color-text-error',
  [Token.ColorTextBalloonTitle]: 'token__swatch--color-text-balloon',
  [Token.ColorTextBalloonLink]: 'token__swatch--color-text-balloon-link',
  [Token.ColorTextBalloonLinkHover]: 'token__swatch--color-text-balloon-link-hover',
  [Token.ColorTextBalloonLinkDisabled]: 'token__swatch--color-text-balloon-link-disabled',
  [Token.ColorTextBalloonLinkAlert]: 'token__swatch--color-text-balloon-link-alert',
  [Token.ColorTextBalloonTooltip]: 'token__swatch--color-text-balloon-tooltip',
  [Token.ColorTextBalloonPurple]: 'token__swatch--color-text-balloon-purple',
  [Token.ColorTextBalloonAlert]: 'token__swatch--color-text-balloon-alert',
  [Token.ColorTextOverlay]: 'token__swatch--color-text-overlay',
  [Token.ColorTextOverlayAlt]: 'token__swatch--color-text-overlay-alt',
  [Token.ColorTextPill]: 'token__swatch--color-text-pill',
  [Token.ColorBorder]: 'token__swatch--color-border',
  [Token.ColorBorderTab]: 'token__swatch--color-border-tab',
  [Token.ColorBorderTabHover]: 'token__swatch--color-border-tab-hover',
  [Token.ColorBorderTabFocus]: 'token__swatch--color-border-tab-focus',
  [Token.ColorBorderTabActive]: 'token__swatch--color-border-tab-active',
  [Token.ColorBorderButton]: 'token__swatch--color-border-button',
  [Token.ColorBorderButtonHover]: 'token__swatch--color-border-button-hover',
  [Token.ColorBorderButtonFocus]: 'token__swatch--color-border-button-focus',
  [Token.ColorBorderButtonActive]: 'token__swatch--color-border-button-active',
  [Token.ColorBorderButtonDisabled]: 'token__swatch--color-border-button-disabled',
  [Token.ColorBorderButtonHollow]: 'token__swatch--color-border-button-hollow',
  [Token.ColorBorderButtonHollowHover]: 'token__swatch--color-border-button-hollow-hover',
  [Token.ColorBorderButtonHollowFocus]: 'token__swatch--color-border-button-hollow-focus',
  [Token.ColorBorderButtonHollowActive]: 'token__swatch--color-border-button-hollow-active',
  [Token.ColorBorderButtonStatus]: 'token__swatch--color-border-button-status',
  [Token.ColorBorderButtonStatusHover]: 'token__swatch--color-border-button-status-hover',
  [Token.ColorBorderButtonStatusFocus]: 'token__swatch--color-border-button-status-focus',
  [Token.ColorBorderButtonStatusActive]: 'token__swatch--color-border-button-status-active',
  [Token.ColorBorderButtonSuccess]: 'token__swatch--color-border-button-success',
  [Token.ColorBorderButtonSuccessHover]: 'token__swatch--color-border-button-success-hover',
  [Token.ColorBorderButtonSuccessFocus]: 'token__swatch--color-border-button-success-focus',
  [Token.ColorBorderButtonSuccessActive]: 'token__swatch--color-border-button-success-active',
  [Token.ColorBorderButtonAlert]: 'token__swatch--color-border-button-alert',
  [Token.ColorBorderButtonAlertHover]: 'token__swatch--color-border-button-alert-hover',
  [Token.ColorBorderButtonAlertFocus]: 'token__swatch--color-border-button-alert-focus',
  [Token.ColorBorderButtonAlertActive]: 'token__swatch--color-border-button-alert-active',
  [Token.ColorBorderInput]: 'token__swatch--color-border-input',
  [Token.ColorBorderInputFocus]: 'token__swatch--color-border-input-focus',
  [Token.ColorBorderInputChecked]: 'token__swatch--color-border-input-checked',
  [Token.ColorBorderInputError]: 'token__swatch--color-border-input-error',
  [Token.ColorBorderToggle]: 'token__swatch--color-border-toggle',
  [Token.ColorBorderToggleHover]: 'token__swatch--color-border-toggle-hover',
  [Token.ColorBorderToggleFocus]: 'token__swatch--color-border-toggle-focus',
  [Token.ColorFill]: 'token__swatch--color-fill',
  [Token.ColorFillCurrent]: 'token__swatch--color-fill-current',
  [Token.ColorFillAlt]: 'token__swatch--color-fill-alt',
  [Token.ColorFillAlt2]: 'token__swatch--color-fill-alt-2',
  [Token.ColorFillBrand]: 'token__swatch--color-fill-brand',
  [Token.ColorFillLive]: 'token__swatch--color-fill-live',
  [Token.ColorFillWarn]: 'token__swatch--color-fill-warn',
  [Token.ColorFillAlert]: 'token__swatch--color-fill-alert',
  [Token.ColorFillSuccess]: 'token__swatch--color-fill-success',
  [Token.ColorFillPrime]: 'token__swatch--color-fill-prime',
  [Token.ColorSocialTwitter]: 'token__swatch--color-social-twitter',
  [Token.ColorSocialFacebook]: 'token__swatch--color-social-facebook',
  [Token.ColorSocialReddit]: 'token__swatch--color-social-reddit',
  [Token.ColorSocialSnapchat]: 'token__swatch--color-social-snapchat',
  [Token.ColorSocialInstagram]: 'token__swatch--color-social-instagram',
  [Token.ColorSocialYoutube]: 'token__swatch--color-social-youtube',
  [Token.ColorSocialPaypal]: 'token__swatch--color-social-paypal',
  [Token.ColorSocialVk]: 'token__swatch--color-social-vk',
  [Token.ShadowButtonFocus]: 'hide',
  [Token.ShadowButtonActive]: 'hide',
  [Token.ShadowButtonDisabled]: 'hide',
  [Token.ShadowInput]: 'hide',
  [Token.ShadowInputFocus]: 'hide',
  [Token.ShadowTabFocus]: 'hide',
  [Token.ShadowBalloon]: 'hide',
  [Token.BorderWidth]: 'hide',
  [Token.BorderRadius]: 'hide',
};

interface Props {
  token?: Token;
  tokenName?: string;
  lightValue?: string;
  darkValue?: string;
}

export const DocumentationToken = (props: Props) => {
  const classes: ClassValue = {};

  if (props.token) {
    classes[TOKEN_CLASSES[props.token]] = true;
  }

  return (
    <div className="token-table-row">
      <div className="token-table-row__cell"><code>{props.tokenName}</code></div>
      <div className="token-table-row__cell">
        <div className="token theme--light">
          <div className={classnames('token__swatch', classes)} {...getDataProps(props)} />
          <code className="token__key">{props.lightValue}</code>
        </div>
      </div>
      <div className="token-table-row__cell">
        <div className="token theme--dark">
          <div className={classnames('token__swatch', classes)} {...getDataProps(props)} />
          <code className="token__key">{props.darkValue}</code>
        </div>
      </div>
    </div>
  );
};
